%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: your\savedir\V1alphasSorted.csv
%
% Auto-generated by MATLAB on 26-Dec-2024 10:39:19

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "section", "alphas", "Var4"];
opts.SelectedVariableNames = ["section", "alphas"];
opts.VariableTypes = ["string", "categorical", "double", "string"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "section", "Var4"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("your\savedir\V1alphasSorted.csv", opts);

%% Convert to output type
section = tbl.section;
alphas = tbl.alphas;

%% Clear temporary variables
clear opts tbl