%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: your\savedir\V1V2betasSorted.csv
%
% Auto-generated by MATLAB on 26-Dec-2024 09:45:41

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "area", "Var3", "layer", "value"];
opts.SelectedVariableNames = ["area", "layer", "value"];
opts.VariableTypes = ["string", "double", "string", "categorical", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3", "layer"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "area", "TrimNonNumeric", true);
opts = setvaropts(opts, "area", "ThousandsSeparator", ",");

% Import the data
tbl = readtable("your\savedir\V1V2betasSorted.csv", opts);

%% Convert to output type
area = tbl.area;
layer = tbl.layer;
value = tbl.value;

%% Clear temporary variables
clear opts tbl