%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: your\savedir\lps.csv
%
% Auto-generated by MATLAB on 24-Dec-2024 15:03:22

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "model", "lp"];
opts.SelectedVariableNames = ["model", "lp"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "model", "TrimNonNumeric", true);
opts = setvaropts(opts, "model", "ThousandsSeparator", ",");

% Import the data
tbl = readtable("your\savedir\lpsSorted.csv", opts);

%% Convert to output type
model = tbl.model;
lp = tbl.lp;

%% Clear temporary variables
clear opts tbl