%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: directory\to\V2_Orientation_Data.xlsx
%    Worksheet: V2
%
% Auto-generated by MATLAB on 23-Dec-2024 10:43:17

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "V2";
opts.DataRange = "A2:G381";

% Specify column names and types
opts.VariableNames = ["Animal", "Section", "Area", "Layer", "RawAngle", "PiaCorrection", "CorrectedAngle"];
opts.SelectedVariableNames = ["Animal", "CorrectedAngle"];
opts.VariableTypes = ["categorical", "char", "char", "char", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["Section", "Area", "Layer"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Animal", "Section", "Area", "Layer"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["RawAngle", "PiaCorrection", "CorrectedAngle"], "TreatAsMissing", '');

% Import the data
tbl = readtable("directory\to\V2_Orientation_Data.xlsx", opts, "UseExcel", false);

%% Convert to output type
Animal = tbl.Animal;
Angle = tbl.CorrectedAngle;

%% Clear temporary variables
clear opts tbl