%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: your\savedir\V1betas.csv
%
% Auto-generated by MATLAB on 23-Dec-2024 16:40:51

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "protein", "layer", "value"];
opts.SelectedVariableNames = ["protein", "layer", "value"];
opts.VariableTypes = ["string", "categorical", "categorical", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "protein", "layer"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("your\savedir\V1betasSorted.csv", opts);

%% Convert to output type
protein = tbl.protein;
layer = tbl.layer;
value = tbl.value;

%% Clear temporary variables
clear opts tbl